question_data = [
    {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
     "question": "Where are the cars of the brand &quot;Ferrari&quot; manufactured?",
     "correct_answer": "Italy", "incorrect_answers": ["Romania", "Germany", "Russia"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following authors was not born in England? ",
     "correct_answer": "Arthur Conan Doyle",
     "incorrect_answers": ["Graham Greene", "H G Wells", "Arthur C Clarke"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
     "question": "How many objects are equivalent to one mole?",
     "correct_answer": "6.022 x 10^23",
     "incorrect_answers": ["6.002 x 10^22", "6.022 x 10^22", "6.002 x 10^23"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which French duo had UK hits in 1998 with the songs &#039;Sexy Boy&#039;, &#039;Kelly Watch The Stars&#039; &amp; &#039;All I Need&#039;?",
     "correct_answer": "Air", "incorrect_answers": ["Fire", "Earth", "Water"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Which Canadian reggae musician had a 1993 hit with the song &#039;Informer&#039;?",
     "correct_answer": "Snow", "incorrect_answers": ["Rain", "Hail", "Sleet"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which band had hits in 1975 with the songs, &#039;One Of These Nights&#039; &amp; &#039;Lyin Eyes&#039;?",
     "correct_answer": "The Eagles",
     "incorrect_answers": ["Fools Gold", "The Doobie Brothers", "Fleetwood Mac"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which American family band had a 1986 top 10 hit with the song &#039;Crush On You&#039;?",
     "correct_answer": "The Jets",
     "incorrect_answers": ["DeBarge", "The Jacksons", "The Cover Girls"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "What is the elemental symbol for mercury?", "correct_answer": "Hg",
     "incorrect_answers": ["Me", "Mc", "Hy"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "medium",
     "question": "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
     "question": "What is the molecular formula of Glucose?",
     "correct_answer": "C6H12O6", "incorrect_answers": ["C2H4O2", "K+", "CH4"]},
    {"category": "Sports", "type": "multiple", "difficulty": "hard",
     "question": "With which doubles partner did John McEnroe have most success?",
     "correct_answer": "Peter Fleming",
     "incorrect_answers": ["Mark Woodforde", "Michael Stich", "Mary Carillo"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "This movie contains the quote, &quot;What we&#039;ve got here is a failure to communicate.&quot;",
     "correct_answer": "Cool Hand Luke",
     "incorrect_answers": ["Bonnie and Clyde", "The Graduate",
                           "In the Heat of the Night"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "When was &quot;YouTube&quot; founded?",
     "correct_answer": "February 14, 2005",
     "incorrect_answers": ["May 22, 2004", "September 12, 2005", "July 19, 2009"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following European languages is classified as a &quot;language isolate?&quot;",
     "correct_answer": "Basque",
     "incorrect_answers": ["Galician", "Maltese", "Hungarian"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following countries does NOT recognize Armenia as an independent country?",
     "correct_answer": "Pakistan",
     "incorrect_answers": ["Iran", "Turkey", "Azerbaijan"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
     "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Windows NT&quot; is a monolithic kernel.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
     "question": "Which of these movies did Jeff Bridges not star in?",
     "correct_answer": "The Hateful Eight",
     "incorrect_answers": ["Tron: Legacy", "The Giver", "True Grit"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
     "difficulty": "medium",
     "question": "In &quot;Shakugan no Shana&quot; what was the Shana usually referred as?",
     "correct_answer": "Flame-Haired Burning-Eyed Hunter",
     "incorrect_answers": ["Flame Haze", "Flame-Haired Burning-Eyed Haze", "Shana"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "What was another suggested name for, the 1985 film, Back to the Future?",
     "correct_answer": "Spaceman From Pluto",
     "incorrect_answers": ["Hill Valley Time Travelers", "The Time Travelers",
                           "The Lucky Man"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "medium",
     "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the area of Vatican City?", "correct_answer": "0.44km^2",
     "incorrect_answers": ["0.10km^2", "0.86km^2", "12.00km^2"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "What does the yellow diamond on the NFPA 704 fire diamond represent?",
     "correct_answer": "Reactivity",
     "incorrect_answers": ["Health", "Flammability", "Radioactivity"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "The element involved in making human blood red is which of the following?",
     "correct_answer": "Iron", "incorrect_answers": ["Copper", "Iridium", "Cobalt"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "Final Fantasy VI was originally released outside Japan under what name?",
     "correct_answer": "Final Fantasy III",
     "incorrect_answers": ["Final Fantasy VI", "Final Fantasy V", "Final Fantasy II"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "In DuckTales, what is the name of the city where all the main characters live?",
     "correct_answer": "Duckburg",
     "incorrect_answers": ["Duckwing", "Tailspin", "Wingford"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "The towns of Brugelette, Arlon and Ath are located in which country?",
     "correct_answer": "Belgium",
     "incorrect_answers": ["Andorra", "France", "Luxembourg"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Which city did the former NHL team &quot;The Nordiques&quot; originiate from?",
     "correct_answer": "Quebec City",
     "incorrect_answers": ["Houston", "Montreal", "New York"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "medium",
     "question": "In the &quot;Harry Potter&quot; novels, what must a Hogwarts student do to enter the Ravenclaw Common Room?",
     "correct_answer": "Answer a riddle",
     "incorrect_answers": ["Rhythmically tap barrels with a wand", "Speak a password",
                           "Knock in sequence"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "Which town was Seamus &quot;Sledge&quot; Cowden from &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; born in?",
     "correct_answer": "John O&#039;Groats",
     "incorrect_answers": ["Brawl", "Kearvaig", "Talmine"]},
    {"category": "History", "type": "boolean", "difficulty": "hard",
     "question": "The USS Missouri (BB-63) last served in the Korean War.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What was the first Android version specifically optimized for tablets?",
     "correct_answer": "Honeycomb",
     "incorrect_answers": ["Eclair", "Froyo", "Marshmellow"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "The set of all algebraic numbers is countable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Celebrities", "type": "multiple", "difficulty": "medium",
     "question": "In what year did &quot;Bob Ross&quot; die?",
     "correct_answer": "1995", "incorrect_answers": ["1986", "1989", "1997"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "multiple",
     "difficulty": "medium",
     "question": "In &quot;The Simpsons&quot;, where did Homer and Marge first meet?",
     "correct_answer": "At Summer Camp",
     "incorrect_answers": ["At High School", "At Church", "At 742 Evergreen Terrace"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "In &quot;Call Of Duty: Zombies&quot;, which map introduced the perk &quot;PhD Flopper&quot;?",
     "correct_answer": "Ascension",
     "incorrect_answers": ["Moon", "Call Of The Dead", "Die Rise"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "hard",
     "question": "Pete Townshend collaborated with which famous guitarist for an event at Brixton Academy in 1985?",
     "correct_answer": "David Gilmour",
     "incorrect_answers": ["Jimmy Page", "Mark Knopfler", "Eric Clapton"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What vulnerability ranked #1 on the OWASP Top 10 in 2013?",
     "correct_answer": "Injection ",
     "incorrect_answers": ["Broken Authentication", "Cross-Site Scripting",
                           "Insecure Direct Object References"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Colchester Overpass, otherwise known as &quot;Bunny Man Bridge&quot;, is located where?",
     "correct_answer": "Fairfax County, Virginia",
     "incorrect_answers": ["Medford, Oregon", "Braxton County, Virgina",
                           "Lemon Grove, California"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital city of Slovenia?",
     "correct_answer": "Ljubljana",
     "incorrect_answers": ["Maribor", "Velenje", "Trbovlje"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "What is the opening track on Lorde&#039;s Pure Heroine?",
     "correct_answer": "Tennis Court",
     "incorrect_answers": ["Team", "Royals", "400 Lux"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "What was Bon Iver&#039;s debut album released in 2007?",
     "correct_answer": "For Emma, Forever Ago",
     "incorrect_answers": ["Bon Iver, Bon Iver", "22, A Million", "Blood Bank EP"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "Psych-Horror &quot;Eternal Darkness: Sanity&#039;s Requiem&quot;, developed by Silicon Knights in 2002, was published by who and on what platform?",
     "correct_answer": "Nintendo&reg; Co. Ltd. | GameCube&trade;",
     "incorrect_answers": [
         "Sony&reg; Computer Entertainment&trade; Inc. | PlayStation&reg; 2",
         "Microsoft&reg; Game Studios&trade; | XBox&trade;",
         "Sega&reg; Enterprises Co. Ltd. | Dreamcast&trade;"]},
    {"category": "Sports", "type": "multiple", "difficulty": "hard",
     "question": "The AHL affiliate team of the Boston Bruins is named what?",
     "correct_answer": "Providence Bruins",
     "incorrect_answers": ["New Haven Bruins", "Cambridge Bruins", "Hartford Bruins"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]

